export const DISALLOWED_HOSTNAMES = [
  SITE.domain,
  "localhost"
];

/** Auto generated by modules/disallowed-brands */
export const DISALLOWED_BRANDS = [
  "about",
  "index",
  "login",
  "signup",
  "app",
  "brand",
  "verify",
  "api",
  "uploads",
  "images"
];
